# Generated by Django 4.2 on 2025-06-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.IntegerField(unique=True)),
                ('status', models.CharField(default='Available', max_length=20)),
                ('reserved', models.BooleanField(default=False)),
                ('reserved_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
